spring:
  sql:
    init:
      mode: always   # 항상 data.sql 실행 # 위험한 옵션!! 개발 DB가 모두 날라갈수 있음으로 주의!
      schema-locations: classpath:hrbank_schema_latest_erd.sql
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:weaverdb}
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER:user1}
    password: ${PGPASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    org.springframework.web: info

server:
  port: ${PORT:8080}